kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: "2,3,4"

title: "You Might Not Need a Library"
description: "Collection of raw HTML, CSS and JS frontend snippets"
google_analytics: UA-75732321-11
